########################################################
# 使用 Spring Runner 运行本程序
########################################################
FROM centralx/spring-runner:17

ARG STUDIO_VERSION

# 复制应用到工作目录
COPY central-bootstrap-${STUDIO_VERSION}.jar application.jar

# 暴露端口
EXPOSE 8080